"""add_drafts_to_task_remove_preview_fk

Revision ID: 0c231f9ebaea
Revises: 20260531_0002
Create Date: 2026-05-31 04:44:17.708066
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c231f9ebaea'
down_revision: Union[str, None] = '20260531_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_tasks', sa.Column('drafts', sa.JSON(), nullable=True))
    op.add_column('publish_tasks', sa.Column('content_ir', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('publish_tasks_preview_id_fkey'), 'publish_tasks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('publish_tasks_preview_id_fkey'), 'publish_tasks', 'previews', ['preview_id'], ['id'], ondelete='CASCADE')
    op.drop_column('publish_tasks', 'content_ir')
    op.drop_column('publish_tasks', 'drafts')
    # ### end Alembic commands ###
